export let items = {
  word1: ["coreldraw", "inkscape", "coinreksldcarapew", "drawing"],
  word2: ["roboform", "keepass", "mssraopfeoebkor", "password manager"],
  word3: ["autocad", "freecad", "ddaacceoetrufa", "drawing software"],
  word4: ["evernote", "nixnote", "eettreveixnono", "note taking"],
  word5: ["ccleaner", "bleachbit","itchleabnaeercbcl","privacy/free diskspace",],
  word6: ["flstudio", "audacity", "fitulauctdasdioy", "Audio editor"],
  word7: ["photoshop", "darktable", "doohtaabptlroekshp", "Graphics/Drawing"],
  word8: ["microsoftoffice","libreoffice", "mooorofffsefctcfilcieibrie", "Office productivity",],
  word9: ["winzip", "peazip", "wzinippzaiep", "Compression tool"],
  word10: ["mcaffe", "clamwin", "mwfalcmcafien", "AntiVirus"],
  word11: ["dreamweaver", "bluefish", "aebedfraadowlviemuebserh","Website creation tool",],
  word12: ["dropbox", "nextcloud", "dxnoxlobtuopercd", "File Hosting"],
  word13: ["googlechrome", "mozillafirefox", "gmroiozleaoeglofomflicherx", "Web Browser"],
  word14: ["googlemaps", "openstreetmaps", "gprleoomeesntpteaaspomgs", "Web Mapping"],
  word15: ["livechat", "chatwoot", "lvattwcochoeiaht", "Online Chat"],
  word16: ["shopify", "magento", "setomhgfnipayo", "E-Commerce"],
  word17: ["firebase", "appwrite", "fpiriptasawbeere", "Mobile and Web apps creation"],
  word18: ["trello", "wekan", "terekllwoan", "Manage Projects"],
  word19: ["slack" "wire", "scriawlke", "Communication Platform"],
  word20: ["whatsapp", "signal", "wasagiapspnthl", "Messaging Service"],
};
