export let items = {
  word1: ["girl", "boy", "golyrbi", "hint1"],
  word2: ["old", "young", "gondylou", "hint2"],
  word3: ["up", "down", "wpnuOd", "hint3"],
  word4: ["CorelDraw","Inkscape","CoInrekslDcarapew","vector drawing program"],
  word5: ["VisioProfessional","Dia","DVPfiaessioisional","creates diagrams—for flowcharts, org charts, and more"],
  word6: ["MicrosoftOffice","OpenOffice","oftOficesorciMnepOOeicff"," Office Productivity"],
  word7: ["RoboForm","KeePass","mssraoPFeoebKoR"," open source password manager"],
  word8: ["AutoCAD","FreeCAD","DDAACCeoetruFA","drawing software"],
  word9: ["Evernote","NixNote","eettrevEixNoNo","help you take notes and stay organized"],
  word10: ["CCleaner","BleachBit","itchleaBnaeerCBCl","guards your privacy and frees disk space"],
  word11: ["FL Studio", "Audacity", "FituLAuctdaSdioy", "Audio editor"],
  word12: ["Photoshop", "Gimp", "PhotsGihoopmp", "Graphics/Drawing"],
  word13: ["Microsoft Office", "Libre Office", "MOoorOfffsefctcfiLcieibrie", "Office Productivity"],
  word14: ["Winzip", "7-Zip", "Wzinip7Zip",	"Compression tool"],
  word15: ["McAffe", "ClamWin", "MWfalcmCAfien",	"AntiVirus"],
  word16: ["AutoDesk Maya",	"Blender", "AyaeBuneteolMadDskr", "3D graphic tool"],
  word17: ["Adobe Dreamweaver", "Bluefish", "AebedfraaDowlviemueBserh", "Website creation tool"], 
};
